lib/irc_web_client_web/router.ex
defmodule IrcWebClientWeb.Router do
  use IrcWebClientWeb, :router
  use Pow.Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    #plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  scope "/api", IrcWebClientWeb do
    pipe_through :api

    #post "/sessions", SessionController, :create
    #resources "/users", UserController, except: [:new, :edit]
  end

  scope "/", Pow.Phoenix, as: "pow" do
    pipe_through :browser

    get "/sign_up", RegistrationController, :new
    post "/sign_up", RegistrationController, :create

    get "/edit_account", RegistrationController, :edit
    put "/edit_account", RegistrationController, :update

    get "/login", SessionController, :new
    post "/login", SessionController, :create

    post "/logout", SessionController, :delete
  end

  scope "/" do
    pipe_through :browser
    pow_routes()
  end

  scope "/", IrcWebClientWeb do
    pipe_through [:browser, :protected]
    get "/", HomePageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", IrcWebClientWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # TODO
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router
    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: IrcWebClientWeb.Telemetry
    end
  end
end

lib/irc_web_client_web/views/pow/registration_view.ex
defmodule IrcWebClientWeb.Pow.RegistrationView do
  use IrcWebClientWeb, :view
end

lib/irc_web_client_web/views/pow/session_view.ex
defmodule IrcWebClientWeb.Pow.SessionView do
  use IrcWebClientWeb, :view
end

lib/irc_web_client_web/views/session_view.ex
defmodule IrcWebClientWeb.SessionView do
  use IrcWebClientWeb, :view

  def render("info.json", %{info: token}) do
    %{access_token: token}
  end
end

lib/irc_web_client_web/templates/pow/session/new.html.eex
<p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
<p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
<div class="w-full max-w-xs mx-auto">
<h1 class="font-large w-full text-gray-800 text-center">Sign in</h1>

<%= form_for @changeset, @action, [as: :user, class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"], fn f -> %>
  <!--<%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>-->

  <div class="mb-4">
    <%= label f, Pow.Ecto.Schema.user_id_field(@changeset),
      class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= text_input f, Pow.Ecto.Schema.user_id_field(@changeset),
      class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    <%= error_tag f, Pow.Ecto.Schema.user_id_field(@changeset) %>
  </div>

  <div class="mb-6">
    <%= label f, :password,
      class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= password_input f, :password,
      class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    <%= error_tag f, :password %>
  </div>

  <div>
    <%= submit "Sign in",  class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>


<span><%= link "Register", to: Routes.pow_registration_path(@conn, :new),
  class: "text-blue-500 hover:text-blue-800"%></span>
</div>